apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ${VAR_ROLE_OCEAN_ARN}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::475721568957:user/amir.misgav1_cli
      username: arn:aws:iam::475721568957:user/amir.misgav1_cli
      groups:
        - system:masters
    - userarn: arn:aws:iam::105968210540:user/amir.misgav_cli
      username: arn:aws:iam::105968210540:user/amir.misgav_cli
      groups:
        - system:masters
    - userarn: arn:aws:iam::105968210540:user/maximni_cli
      username: arn:aws:iam::105968210540:user/maximni_cli
      groups:
        - system:masters
    - userarn: arn:aws:iam::475721568957:user/alexcher_cli
      username: arn:aws:iam::475721568957:user/alexcher_cli
      groups:
        - system:masters
    - userarn: arn:aws:iam::105968210540:user/alexcher_cli
      username: arn:aws:iam::105968210540:user/alexcher_cli
      groups:
        - system:masters
    - userarn: arn:aws:iam::105968210540:user/mhaim_cli
      username: arn:aws:iam::105968210540:user/mhaim_cli
      groups:
        - system:masters
    - userarn: ${OPS_USER}
      username: ${OPS_USER}
      groups:
        - system:masters
  mapAccounts: |
    - "trusteer-aws-qa"
